/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package Ventanas;

import DB.coneccion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ivan
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    static Connection cnn=null;
  static Statement sta=null;
  static ResultSet rst=null;
  
    void validar(){
         String usuario=txt_usuario.getText();
        String pass=String.valueOf(txtpass_contraseña.getPassword());
        String sql="select * from usuarios where User='"+usuario+"' and Password='"+pass+"' ";
       cnn=coneccion.enlace(cnn);
        sta=coneccion.declaracion(sta);
         try {
         
          rst=sta.executeQuery(sql);
        
        if(usuario.equalsIgnoreCase("")|| pass.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"Faltan Ingresar Datos");
            
        }else{
           
                if(rst.next()){
                    Menu_Principal Menu=new Menu_Principal();
                    Menu.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos");
                    txt_usuario.setText("");
                    txtpass_contraseña.setText("");
                    txt_usuario.requestFocus();
                }
            }
         }
        
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Estas cometiendo un error");
            }

    }
    public login() {
        initComponents();
        //kitamos la opciones de maximizar y cerrar
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/gaman.jpeg"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_salir = new javax.swing.JButton();
        jlb_logo = new javax.swing.JLabel();
        jlb_user = new javax.swing.JLabel();
        jlb_pass = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txtpass_contraseña = new javax.swing.JPasswordField();
        btn_iniciar = new javax.swing.JButton();
        jbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setBackground(new java.awt.Color(204, 0, 0));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 70, -1));

        jlb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        getContentPane().add(jlb_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jlb_user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlb_user.setForeground(new java.awt.Color(255, 255, 255));
        jlb_user.setText("Usuario:");
        getContentPane().add(jlb_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jlb_pass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlb_pass.setForeground(new java.awt.Color(255, 255, 255));
        jlb_pass.setText("Password:");
        getContentPane().add(jlb_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        txt_usuario.setBackground(new java.awt.Color(0, 0, 153));
        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, 30));

        txtpass_contraseña.setBackground(new java.awt.Color(0, 0, 153));
        txtpass_contraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpass_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtpass_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass_contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 160, 30));

        btn_iniciar.setBackground(new java.awt.Color(0, 0, 153));
        btn_iniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        btn_iniciar.setText("Iniciar Sesion");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 355, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txtpass_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass_contraseñaActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        // TODO add your handling code here:
         validar();
    }//GEN-LAST:event_btn_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jbl_fondo;
    private javax.swing.JLabel jlb_logo;
    private javax.swing.JLabel jlb_pass;
    private javax.swing.JLabel jlb_user;
    public static javax.swing.JTextField txt_usuario;
    public static javax.swing.JPasswordField txtpass_contraseña;
    // End of variables declaration//GEN-END:variables
}
